name: Build and Publish to Maven Remotely

on:
  workflow_call:
    inputs:
      package-name:
        description: "Package name"
        type: string
        required: true
      destination-repository:
        description: "Publishing destination repository"
        type: string
        required: true

jobs:
  publish:
    name: Build and Publish to Maven Remotely
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Setup secrets
        run: bash ./.github/scripts/setup_secrets.sh "${{ secrets.MAPBOX_SECRET_TOKEN }}" "${{ secrets.GOOGLE_MAPS_API_KEY }}" "${{ secrets.MAPBOX_PUBLIC_TOKEN }}" "${{ secrets.AZURE_MAPS_SUBSCRIPTION_KEY }}"

      - name: Set useLocalProjects flag
        run: echo useLocalProjects=true >> local.properties

      - name: "Setup target repository: ${{ inputs.destination-repository }}"
        run: bash ./.github/scripts/setup_publishing_repository_property.sh ${{ inputs.destination-repository }}

      - name: Release build
        run: ./gradlew ${{ inputs.package-name }}:assembleRelease

      # Runs upload to the snapshot repository
      - name: Publish to snapshot area
        run: ./gradlew ${{ inputs.package-name }}:publishReleasePublicationToSonatypeRepository --max-workers 1
        env:
          OSSRH_USERNAME: 'test'
          OSSRH_PASSWORD: 'test'
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
