name: Build and Deploy Documentation

on:
  workflow_call:
    inputs:
      input-cache-prefix:
        description: "Input cache prefix"
        type: string
        required: false
        default: ""
      output-cache-prefix:
        description: "Output cache prefix"
        type: string
        required: false
        default: ""

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Update local properties for secrets
        run: echo MAPS_API_KEY= ${{ secrets.GOOGLE_MAPS_API_KEY }} > ./local.properties

      - name: Set useMavenLocal flag
        run: echo useMavenLocal=true >> local.properties

      - name: Restore MavenLocal Cache
        if: ${{ inputs.input-cache-prefix != '' }}
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ inputs.input-cache-prefix }}-${{ github.run_id }}

      - name: Build documentation using Dokka
        run: ./gradlew dokkaHtmlMultiModule

      - name: Cache MavenLocal
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ inputs.output-cache-prefix }}-${{ github.run_id }}

  deploy:
    name: Deploy documentation to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    # GITHUB_TOKEN needs to be granted the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
