name: Temp Debug Workflow

on: push

jobs:

  # Build and publish only core package to MavenLocal
  # this artifact is used by publish_sample_app.yml
  maps-core-local:
    name: Publish Core Package to Maven Local
    uses: ./.github/workflows/build_and_publish_to_maven_local.yml
    with:
      output-cache-prefix: mavenLocal-core
      gradle-command: "publishCoreToMavenLocal"
    secrets: inherit

  # Build and publish only core package to Sonatype
  # this workflow uses local projects
  maps-core-remote:
    needs: maps-core-local
    name: Publish Core Package to Sonatype
    uses: ./.github/workflows/build_and_publish_to_maven_remotely.yml
    with:
      package-name: :packages:core
      destination-repository: snapshot
    secrets: inherit