name: Android CD

on:
  push:
    branches: [ build/sample-app-pipelines ]

jobs:
  maps-core:
    uses: ./.github/workflows/publish_maps_api.yml
    secrets: inherit

  maps-plugin-gms:
    needs: maps-core
    runs-on: ubuntu-latest
    steps:
    - name: Publish Maps Plugin GMS
      run: echo "maps-plugin-gms steps"

  maps-plugin-non-gms:
    needs: maps-core
    runs-on: ubuntu-latest
    steps:
    - name: Publish Maps Plugin Non-GMS
      run: echo "Running maps-plugin-non-gms steps"

  maps-app:
    needs: [maps-plugin-gms, maps-plugin-non-gms]
    uses: ./.github/workflows/publish_sample_app.yml
    secrets: inherit