# This workflow combines 3 workflows into one to provide a correct sequence of actions.
# Build and publishing Sample App needs to wait for all other workflows to complete.
# It was not possible when using separate workflows and the `workflow_run` events
# as the workflow_run event is triggered when the first workflow is completed.
# See the discussion here: https://github.com/orgs/community/discussions/16059

name: Android CD

on:
  push:
    branches: [ build/sample-app-pipelines ]

jobs:
  maps-core:
    uses: ./.github/workflows/build_and_publish_to_maven_local.yml
    with:
      output-cache-prefix: mavenLocal-core
      release-build-command: ':packages:maps-api:assembleRelease'
      publish-to-maven-local-command: ':packages:maps-api:publishToMavenLocal'
    secrets: inherit
    

  maps-plugins:
    needs: maps-core
    uses: ./.github/workflows/build_and_publish_to_maven_local.yml
    with:
      input-cache-prefix: mavenLocal-core
      output-cache-prefix: mavenLocal-core-and-plugins
      release-build-command: 'assembleRelease'
      publish-to-maven-local-command: 'publishToMavenLocal'
    secrets: inherit

  maps-app:
    needs: maps-plugins
    uses: ./.github/workflows/publish_sample_app.yml
    secrets: inherit
