name: Android CI

on:
  pull_request:
    branches: [main, develop, "release/**"]
    types: [opened, synchronize]

jobs:
  # Build and publish only core package to MavenLocal
  maps-core:
    uses: ./.github/workflows/build_and_publish_to_maven_local.yml
    with:
      output-cache-prefix: mavenLocal-core
      gradle-command: "publishCoreToMavenLocal"
    secrets: inherit

  # Build and publish all plugins to MavenLocal
  maps-plugins:
    needs: maps-core
    uses: ./.github/workflows/build_and_publish_to_maven_local.yml
    with:
      input-cache-prefix: mavenLocal-core
      output-cache-prefix: mavenLocal-core-and-plugins
      gradle-command: "publishPluginsToMavenLocal"
    secrets: inherit

  # Assemble sample app
  assemble_modules:
    name: Assemble modules
    needs: maps-plugins
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Setup secrets
        run: bash ./.github/scripts/setup_secrets.sh "${{ secrets.MAPBOX_SECRET_TOKEN }}" "${{ secrets.GOOGLE_MAPS_API_KEY }}" "${{ secrets.MAPBOX_PUBLIC_TOKEN }}" "${{ secrets.AZURE_MAPS_SUBSCRIPTION_KEY }}"

      - name: Set useMavenLocal flag
        run: echo useMavenLocal=true >> local.properties

      - name: Restore Cache MavenLocal
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: mavenLocal-core-and-plugins-${{ github.run_id }}

      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug

  code_quality_analysis:
    name: Check code quality
    needs: maps-plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Setup secrets
        run: bash ./.github/scripts/setup_secrets.sh "${{ secrets.MAPBOX_SECRET_TOKEN }}" "${{ secrets.GOOGLE_MAPS_API_KEY }}" "${{ secrets.MAPBOX_PUBLIC_TOKEN }}" "${{ secrets.AZURE_MAPS_SUBSCRIPTION_KEY }}"

      - name: Set useMavenLocal flag
        run: echo useMavenLocal=true >> local.properties

      - name: Restore Cache MavenLocal
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: mavenLocal-core-and-plugins-${{ github.run_id }}

      - name: Misspelling on detekt + ktlint
        run: bash ./gradlew detekt --stacktrace --continue

      - name: Run unit tests and check coverage
        run: bash ./gradlew jacocoCoverageVerification --stacktrace --continue
