# This workflow combines 4 workflows into one to provide a correct sequence of actions.
# Build and publishing Sample App needs to wait for all other workflows to complete.
# It was not possible when using separate workflows and the `workflow_run` events
# as the workflow_run event is triggered when the first workflow is completed.
# See the discussion here: https://github.com/orgs/community/discussions/16059

name: Android CD

on:
  push:
    branches: [ build/sample-app-pipelines ]

jobs:
  maps-core:
    uses: ./.github/workflows/publish_maps_api.yml
    secrets: inherit

  maps-plugin-gms:
    needs: maps-core
    uses: ./.github/workflows/publish_maps_api_gms.yml
    secrets: inherit

  maps-plugin-non-gms:
    needs: maps-core
    uses: ./.github/workflows/publish_maps_api_ngms.yml
    secrets: inherit

  maps-app:
    needs: [maps-plugin-gms, maps-plugin-non-gms]
    uses: ./.github/workflows/publish_sample_app.yml
    secrets: inherit
