# This workflow combines 3 workflows into one to provide a correct sequence of actions.
# Build and publishing Sample App needs to wait for all other workflows to complete.

name: Android CD

on:
  push:
    branches: [main]

# GITHUB_TOKEN needs to be granted the permissions required to make a Pages deployment
permissions:
  contents: read
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  # Build and publish only core package to MavenLocal
  # this artifact is used by publish_sample_app.yml
  maps-core-local:
    name: Publish Core Package to Maven Local
    uses: ./.github/workflows/build_and_publish_to_maven_local.yml
    with:
      output-cache-prefix: mavenLocal-core
      gradle-command: "publishCoreToMavenLocal"
    secrets: inherit

  # Build and publish all plugins to MavenLocal
  # these artifacts are used by publish_sample_app.yml
  maps-plugins-local:
    needs: maps-core-local
    name: Publish Plugins to Maven Local
    uses: ./.github/workflows/build_and_publish_to_maven_local.yml
    with:
      input-cache-prefix: mavenLocal-core
      output-cache-prefix: mavenLocal-core-and-plugins
      gradle-command: "publishPluginsToMavenLocal"
    secrets: inherit

  # Build and publish only core package to Sonatype
  # this workflow uses local projects
  maps-core-remote:
    needs: maps-core-local
    name: Publish Core Package to Sonatype
    uses: ./.github/workflows/build_and_publish_to_maven_remotely.yml
    with:
      package-name: :packages:core
      destination-repository: snapshot
    secrets: inherit

  # Build and publish snapshots of all plugins to Sonatype
  # this workflow uses local projects
  maps-plugins-remote:
    needs: maps-plugins-local
    name: Publish snapshots of Plugins to Sonatype
    secrets: inherit
    strategy:
      matrix:
        plugin-name:
          [
            "plugin-googlemaps",
            "plugin-openstreetmap",
            "plugin-mapbox",
            "plugin-azuremaps",
          ]
    uses: ./.github/workflows/build_and_publish_to_maven_remotely.yml
    with:
      package-name: :packages:${{ matrix.plugin-name }}
      destination-repository: snapshot

  # Build and publish Sample App
  # this workflow uses Maven Local artifacts
  maps-app:
    needs: maps-plugins-local
    uses: ./.github/workflows/publish_sample_app.yml
    with:
      input-cache-prefix: mavenLocal-core-and-plugins
    secrets: inherit

  build_and_publish_docs:
    needs: maps-plugins-local
    uses: ./.github/workflows/build_and_publish_docs.yml
    secrets: inherit
    if: "contains(github.event.head_commit.message, 'release')"

