name: Publish OpenStreetMap Plugin

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish OpenStreetMap Plugin
    uses: ./.github/workflows/build_and_publish_to_maven_remotely.yml
    with:
      package-name: packages:plugin-openstreetmap
    secrets: inherit
