name: Build and Publish Sample App

on:
  push:
    branches: [build/sample-app-pipelines]

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    env:
      SAMPLE_APP_PATH: "./apps/maps-sample"
      GRADLE_ASSEMBLE_TASK: ":apps:maps-sample:assembleReleaseSingleBuild"
      APK_PATH: "./apps/maps-sample/build/outputs/apk/releaseSingleBuild/maps-sample-releaseSingleBuild.apk"

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
      - name: Update local properties for secrets
        run: echo MAPS_API_KEY="MAPS_API_KEY_VALUE" > ./local.properties # To be replaced with API key from secrets
      - name: Decode keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileDir: ${{ env.SAMPLE_APP_PATH }}
          fileName: ${{ secrets.SAMPLE_APP_KEYSTORE_FILE_NAME }}
          encodedString: ${{ secrets.SAMPLE_APP_KEYSTORE_BASE_64 }}
      - name: Assemble release app
        run: bash ./gradlew ${{ env.GRADLE_ASSEMBLE_TASK }}
        env:
          SAMPLE_APP_KEYSTORE_FILE_NAME: ${{ secrets.SAMPLE_APP_KEYSTORE_FILE_NAME }}
          SAMPLE_APP_KEYSTORE_STORE_PASSWORD: ${{ secrets.SAMPLE_APP_KEYSTORE_STORE_PASSWORD }}
          SAMPLE_APP_KEYSTORE_KEY_ALIAS: ${{ secrets.SAMPLE_APP_KEYSTORE_KEY_ALIAS }}
          SAMPLE_APP_KEYSTORE_KEY_PASSWORD: ${{ secrets.SAMPLE_APP_KEYSTORE_KEY_PASSWORD }}
      - name: Publish app to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ secrets.APP_CENTER_APP_NAME }}
          group: ${{ secrets.APP_CENTER_GROUP }}
          token: ${{ secrets.APP_CENTER_TOKEN }}
          file: ${{ env.APK_PATH }}
          notifyTesters: true
          debug: true
